name: Build

on: push

jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Start buld
        run: echo "Build starting..."

  build:
    needs: code_quality
    runs-on: windows-latest

    steps:
      - name: Build
        run: yarn build
